#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/redmi/begonia

PRODUCT_COPY_FILES += \
    vendor/redmi/begonia/proprietary/system/etc/init/init.vtservice.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/init.vtservice.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/redmi/begonia/proprietary/vendor/etc/.tp/.thermal_policy_08:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_08 \
    vendor/redmi/begonia/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/CFR_para_T.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_T.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/CFR_para_UW.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/CFR_para_W.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/LDC_packdata_xiaomi_G7_src1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_packdata_xiaomi_G7_src1.dat \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/apu_miai_capture.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_capture.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/apu_miai_fragment.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_fragment.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/apu_miai_preview.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/apu_miai_preview.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/beauty_ui9_intelligent_params.config:$(TARGET_COPY_OUT_VENDOR)/etc/camera/beauty_ui9_intelligent_params.config \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/golden_rear_dc_cal_wt.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/golden_rear_dc_cal_wt.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/libalfpc_tuning_20181222.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/libalfpc_tuning_20181222.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/redmi/begonia/proprietary/vendor/etc/camera/visidon_clearshot_params_algoup.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/visidon_clearshot_params_algoup.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/csot_fhd_nt36672a_dsi_vdo_lcm_drv_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/csot_fhd_nt36672a_dsi_vdo_lcm_drv_mi.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/default_pd_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/etc/default_pd_calibration.bin \
    vendor/redmi/begonia/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ebbg_fhd_ft8719_dsi_vdo_lcm_drv_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ebbg_fhd_ft8719_dsi_vdo_lcm_drv_mi.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-mediatek.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service.beanpod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service.beanpod.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-mtk-neuron.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.sensors@1.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@1.0-service-mediatek.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.mtk.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/android.hardware.usb@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.1-service-mediatek.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/em_hidl_user.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/em_hidl_user.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.batteryd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.batteryd.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.cccifsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccifsd.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.mfp-daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.mfp-daemon.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init.xcap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.xcap.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/init_connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_connectivity.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/microtrust.bp_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.bp_kmsetkey_ca.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/microtrust_begonia.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust_begonia.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.mediatek.hardware.dfps@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.dfps@1.0-service.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.mediatek.hardware.gpu@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.gpu@1.0-service.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.5-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.5-service.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkcodecservice@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkcodecservice@1.1-service.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vendor.microtrust.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.microtrust.hardware.soter@1.0-service.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/vpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vpud.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/redmi/begonia/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_RF.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/redmi/begonia/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/spn-conf-op09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/spn-conf-op09.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-arvr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-arvr.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-camera.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-chg-only.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-chg-only.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermal-youtube.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-youtube.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/redmi/begonia/proprietary/vendor/etc/tianma_fhd_nt36672a_dsi_vdo_lcm_drv_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/tianma_fhd_nt36672a_dsi_vdo_lcm_drv_mi.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/redmi/begonia/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/redmi/begonia/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/redmi/begonia/proprietary/vendor/firmware/FT8719_G7_TestINI.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/FT8719_G7_TestINI.ini \
    vendor/redmi/begonia/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_5920.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_5920.csv \
    vendor/redmi/begonia/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_5921.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_5921.csv \
    vendor/redmi/begonia/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_2a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_2a_1.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/redmi/begonia/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/redmi/begonia/proprietary/vendor/firmware/gt1151_default_firmware2.img:$(TARGET_COPY_OUT_VENDOR)/firmware/gt1151_default_firmware2.img \
    vendor/redmi/begonia/proprietary/vendor/firmware/gt9886_cfg_6785v96.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v96.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/gt9886_cfg_6785v99.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v99.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/gt9886_firmware_6785a4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785a4.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/gt9886_firmware_6785ae.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785ae.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/mono.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/mono.cnt \
    vendor/redmi/begonia/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/soc1_0_patch_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_2a_1_hdr.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/soc1_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_1a_1_hdr.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/soc1_0_ram_bt_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_2a_1_hdr.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/soc1_0_ram_mcu_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_2a_1_hdr.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/soc1_0_ram_wifi_2a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_2a_1_hdr.bin \
    vendor/redmi/begonia/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/redmi/begonia/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/redmi/begonia/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/0102030405060708090a0b0c0d0e0f10.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/0102030405060708090a0b0c0d0e0f10.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/020b0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020b0000000000000000000000000000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/020f0000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/020f0000000000000000000000000000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/05120000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/05120000000000000000000000000000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/07060000000000000000000000007169.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/07060000000000000000000000007169.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/07407000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/07407000000000000000000000000000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/08010203000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08010203000000000000000000000000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/08020000000000000000000000007169.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08020000000000000000000000007169.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/08030000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08030000000000000000000000000000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/08070000000000000000000000008270.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/08070000000000000000000000008270.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/09010000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/09010000000000000000000000000000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/09030000000000000000000000008270.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/09030000000000000000000000008270.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/0f5eed3c3b5a47afacca69a84bf0efad.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/0f5eed3c3b5a47afacca69a84bf0efad.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/14498ace2a8f11e880c8509a4c146f4c.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/3d08821c33a611e6a1fa089e01c83aa2.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/40188311faf343488db888ad39496f9a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/40188311faf343488db888ad39496f9a.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/5020170115e016302017012521300000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/5020170115e016302017012521300000.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/57f02fe81d5a11ea8d23d7abe98b8462.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/57f02fe81d5a11ea8d23d7abe98b8462.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/7b66512021214487ba710a51d7ea78fe.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7b66512021214487ba710a51d7ea78fe.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/85f630e0f0964c5fa2cc268ce04e3da3.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/85f630e0f0964c5fa2cc268ce04e3da3.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/9073f03a9618383bb1856eb3f990babd.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/9073f03a9618383bb1856eb3f990babd.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/98fb95bcb4bf42d26473eae48690d7ea.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/98fb95bcb4bf42d26473eae48690d7ea.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/a985d3eb3b524d44be6c628a813561e8.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/a985d3eb3b524d44be6c628a813561e8.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/b09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/b09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e5140b3376fa4c63ab18062caab2fb5c.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/e97c270ea5c44c58bcd3384a2fa2539e.ta \
    vendor/redmi/begonia/proprietary/vendor/thh/ta/fc32e4da17d342449b01c992d56d71bf.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/fc32e4da17d342449b01c992d56d71bf.ta

PRODUCT_PACKAGES += \
    libem_support_jni \
    libcomutils \
    libimsma \
    libimsma_adapt \
    libimsma_rtp \
    libimsma_socketwrapper \
    libmtk_vt_service \
    libmtk_vt_wrapper \
    libmtkavenhancements \
    libsignal \
    libsink-mtk \
    libsource \
    libvcodec_cap \
    libvcodec_capenc \
    libvt_avsync \
    arm.graphics-V1-ndk_platform \
    libGLES_mali \
    libGLES_meow \
    libMEOW_gift \
    libMEOW_trace \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    android.hardware.thermal@2.0-impl \
    dfps.mt6785 \
    nfc_nci.nqx.default \
    thermal.mt6785 \
    vendor.mediatek.hardware.dfps@1.0-impl \
    vendor.mediatek.hardware.mms@1.5-impl \
    vendor.mediatek.hardware.pq@2.6-impl \
    libDefaultFpsActor \
    libFrameRecord \
    libJpgEncPipe \
    libNoFpsActor \
    libOpenCL \
    libTEECommon \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libaalservice \
    libbwc \
    libcapctrl \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcrypto-md \
    libcrypto-ss \
    libcurl-md \
    libcurl-ss \
    libcustom_nvram \
    libdapparamstorage \
    libdeccfg \
    libdpframework \
    libdre \
    libfile_op \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgz_gp_client \
    libgz_uree \
    libhdrvideo \
    libhwm \
    libhydra \
    libimsg_log \
    libion_mtk \
    libion_ulit \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libladder \
    libmtcloader \
    libmtk_drvb \
    libmtkares \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtksysutils \
    libnvram \
    libnvram_daemon_callback \
    libnvram_platform \
    libnvram_sec \
    libpq_cust_base \
    libpq_prot \
    libsimaka \
    libssl-md \
    libssl-ss \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libstagefrightdolby \
    libstrongswan \
    libsysenv \
    libthha \
    libudf \
    libverno \
    libvpu \
    libwo \
    nfc_nci.nqx.default.hw \
    libswdap \
    libswgamedap \
    libswvqe \
    vendor.dolby.hardware.dms@2.0 \
    vendor.mediatek.hardware.dfps@1.0 \
    vendor.mediatek.hardware.gpu@1.0 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.xiaomi.hardware.citsensorservice@1.0 \
    vendor.xiaomi.hardware.citsensorservice@1.1 \
    AVCSecureVdecCA \
    VP9SecureVdecCA \
    audio.primary.mt6785 \
    sound_trigger.primary.mt6785 \
    vendor.mediatek.hardware.mtkcodecservice@1.1-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    libDR \
    libHEVCdec_sa.ca7.android \
    libMtkSpeechEnh \
    lib_iir \
    lib_smartpa_nxp_ap \
    lib_speech_enh \
    libalsautils-v30 \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libcharon-ss \
    libcvsd_mtk \
    libfgauge_gm30 \
    libfvaudio \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264enc_sa.ca7 \
    libipsec_ims_shr \
    libmnl \
    libmp4enc_sa.ca7 \
    libmsbc_mtk \
    libmtklimiter_vendor \
    libmtkshifter_vendor \
    libnxp_extamp_intf \
    liboemcrypto \
    librpc \
    libsn100u_fw \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstorage_otp \
    libthermalalgo \
    libtlcWidevineModularDrm \
    libvc1dec_sa.ca7 \
    libvcodec_oal \
    libvcodec_utility \
    libvcodecdrv \
    libviagpsrpc \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvow_ap_testing.vendor \
    libvowp23_sid_testing.vendor \
    libvowp23_sid_training.vendor \
    libvowp25testing.vendor \
    libvowp2training.vendor \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvpud_vcodec \
    libvt_custom \
    libwapi \
    libwvhidl \
    libwvdrmengine \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.mtkcodecservice@1.1 \
    vendor.mediatek.hardware.videotelephony@1.0-vendor \
    APUWareUtilsServer \
    APUWareXrpServer \
    gc2375af_mipi_raw_IdxMgr \
    gc2375af_mipi_raw_tuning \
    gc2375alpha_mipi_raw_IdxMgr \
    gc2375alpha_mipi_raw_tuning \
    gc2375beta_mipi_raw_IdxMgr \
    gc2375beta_mipi_raw_tuning \
    gc5035_mipi_raw_IdxMgr \
    gc5035_mipi_raw_tuning \
    android.hardware.camera.provider@2.4-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.sensors@1.0-impl-mediatek \
    consumerir.mt6785 \
    fpc_fingerprint.default \
    gatekeeper.beanpod \
    gf_fingerprint.default \
    gps.default \
    hwcomposer.mt6785 \
    kmsetkey.beanpod \
    sensors.mt6785 \
    sensors.touch \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.camera.postproc@1.0-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.core \
    lib3a.af \
    lib3a.awb.core \
    lib3a.awb \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.flash \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    libCamera_gc2375afmipiraw_Flash_Capture \
    libCamera_gc2375afmipiraw_Flash_Preview_PF \
    libCamera_gc2375afmipiraw_HDR_Capture \
    libCamera_gc2375afmipiraw_MFSR_Capture \
    libCamera_gc2375afmipiraw_Reserved \
    libCamera_gc2375afmipiraw_Scene_Capture \
    libCamera_gc2375afmipiraw_Scene_Preview \
    libCamera_gc2375afmipiraw_Video_Preview \
    libCamera_gc2375afmipiraw_Zoom_Preview \
    libCamera_gc2375alphamipiraw_Reserved \
    libCamera_gc2375alphamipiraw_Scene_Capture \
    libCamera_gc2375alphamipiraw_Scene_Preview \
    libCamera_gc2375betamipiraw_Reserved \
    libCamera_gc2375betamipiraw_Scene_Capture \
    libCamera_gc2375betamipiraw_Scene_Preview \
    libCamera_gc5035mipiraw_Reserved \
    libCamera_gc5035mipiraw_Scene_Capture \
    libCamera_gc5035mipiraw_Scene_Preview \
    libCamera_ov02a10afmipiraw_Flash_Capture \
    libCamera_ov02a10afmipiraw_Flash_Preview_PF \
    libCamera_ov02a10afmipiraw_HDR_Capture \
    libCamera_ov02a10afmipiraw_MFSR_Capture \
    libCamera_ov02a10afmipiraw_Reserved \
    libCamera_ov02a10afmipiraw_Scene_Capture \
    libCamera_ov02a10afmipiraw_Scene_Preview \
    libCamera_ov02a10afmipiraw_Video_Preview \
    libCamera_ov02a10afmipiraw_Zoom_Preview \
    libCamera_ov02a10alphamipiraw_Reserved \
    libCamera_ov02a10alphamipiraw_Scene_Capture \
    libCamera_ov02a10alphamipiraw_Scene_Preview \
    libCamera_ov02a10betamipiraw_Reserved \
    libCamera_ov02a10betamipiraw_Scene_Capture \
    libCamera_ov02a10betamipiraw_Scene_Preview \
    libCamera_ov8856ofilmmipiraw_Face_Capture \
    libCamera_ov8856ofilmmipiraw_Flash_Capture \
    libCamera_ov8856ofilmmipiraw_Flash_Preview_PF \
    libCamera_ov8856ofilmmipiraw_HDR_Capture \
    libCamera_ov8856ofilmmipiraw_Reserved \
    libCamera_ov8856ofilmmipiraw_Scene_Capture \
    libCamera_ov8856ofilmmipiraw_Scene_Preview \
    libCamera_ov8856ofilmmipiraw_Video720P_Face_Preview \
    libCamera_ov8856ofilmmipiraw_Video720P_Preview \
    libCamera_ov8856ofilmmipiraw_Video_Face_Preview \
    libCamera_ov8856ofilmmipiraw_Video_Face_Preview_EIS \
    libCamera_ov8856ofilmmipiraw_Video_Preview \
    libCamera_ov8856ofilmmipiraw_Video_Preview_EIS \
    libCamera_ov8856ofilmmipiraw_Zoom_Preview \
    libCamera_ov8856ofilmmipiraw_Zoom_Video \
    libCamera_ov8856ofilmmipiraw_Zoom_Video720P \
    libCamera_ov8856ofilmmipiraw_Zoom_Video720P_2 \
    libCamera_ov8856ofilmmipiraw_Zoom_Video_2 \
    libCamera_ov8856ofilmmipiraw_Zoom_Video_EIS \
    libCamera_ov8856ofilmmipiraw_Zoom_Video_EIS_2 \
    libCamera_ov8856sunnymipiraw_Face_Capture \
    libCamera_ov8856sunnymipiraw_Flash_Capture \
    libCamera_ov8856sunnymipiraw_Flash_Preview_PF \
    libCamera_ov8856sunnymipiraw_HDR_Capture \
    libCamera_ov8856sunnymipiraw_Reserved \
    libCamera_ov8856sunnymipiraw_Scene_Capture \
    libCamera_ov8856sunnymipiraw_Scene_Preview \
    libCamera_ov8856sunnymipiraw_Video720P_Face_Preview \
    libCamera_ov8856sunnymipiraw_Video720P_Preview \
    libCamera_ov8856sunnymipiraw_Video_Face_Preview \
    libCamera_ov8856sunnymipiraw_Video_Face_Preview_EIS \
    libCamera_ov8856sunnymipiraw_Video_Preview \
    libCamera_ov8856sunnymipiraw_Video_Preview_EIS \
    libCamera_ov8856sunnymipiraw_Zoom_Preview \
    libCamera_ov8856sunnymipiraw_Zoom_Video \
    libCamera_ov8856sunnymipiraw_Zoom_Video720P \
    libCamera_ov8856sunnymipiraw_Zoom_Video720P_2 \
    libCamera_ov8856sunnymipiraw_Zoom_Video_2 \
    libCamera_ov8856sunnymipiraw_Zoom_Video_EIS \
    libCamera_ov8856sunnymipiraw_Zoom_Video_EIS_2 \
    libCamera_s5k3t1ofilmmipiraw_3rd_Capture \
    libCamera_s5k3t1ofilmmipiraw_3rd_Preview \
    libCamera_s5k3t1ofilmmipiraw_AutoHDR_Capture \
    libCamera_s5k3t1ofilmmipiraw_FaceUnlock_Capture \
    libCamera_s5k3t1ofilmmipiraw_Face_Capture \
    libCamera_s5k3t1ofilmmipiraw_Portrait_Preview \
    libCamera_s5k3t1ofilmmipiraw_QQ_Capture_1080P \
    libCamera_s5k3t1ofilmmipiraw_QQ_Capture_480P \
    libCamera_s5k3t1ofilmmipiraw_Reserved \
    libCamera_s5k3t1ofilmmipiraw_Scene_Capture \
    libCamera_s5k3t1ofilmmipiraw_Scene_Preview \
    libCamera_s5k3t1ofilmmipiraw_Scene_Video \
    libCamera_s5k3t1ofilmmipiraw_YUV_Reprocess \
    libCamera_s5k3t1sunnymipiraw_3rd_Capture \
    libCamera_s5k3t1sunnymipiraw_3rd_Preview \
    libCamera_s5k3t1sunnymipiraw_AutoHDR_Capture \
    libCamera_s5k3t1sunnymipiraw_FaceUnlock_Capture \
    libCamera_s5k3t1sunnymipiraw_Face_Capture \
    libCamera_s5k3t1sunnymipiraw_Portrait_Preview \
    libCamera_s5k3t1sunnymipiraw_QQ_Capture_1080P \
    libCamera_s5k3t1sunnymipiraw_QQ_Capture_480P \
    libCamera_s5k3t1sunnymipiraw_Reserved \
    libCamera_s5k3t1sunnymipiraw_Scene_Capture \
    libCamera_s5k3t1sunnymipiraw_Scene_Preview \
    libCamera_s5k3t1sunnymipiraw_Scene_Video \
    libCamera_s5k3t1sunnymipiraw_YUV_Reprocess \
    libCamera_s5k3t2mipiraw_3rd_Capture \
    libCamera_s5k3t2mipiraw_3rd_Preview \
    libCamera_s5k3t2mipiraw_AutoHDR_Capture \
    libCamera_s5k3t2mipiraw_FaceUnlock_Capture \
    libCamera_s5k3t2mipiraw_Face_Capture \
    libCamera_s5k3t2mipiraw_Portrait_Preview \
    libCamera_s5k3t2mipiraw_QQ_Capture_1080P \
    libCamera_s5k3t2mipiraw_QQ_Capture_480P \
    libCamera_s5k3t2mipiraw_Reserved \
    libCamera_s5k3t2mipiraw_Scene_Capture \
    libCamera_s5k3t2mipiraw_Scene_Preview \
    libCamera_s5k3t2mipiraw_Scene_Video \
    libCamera_s5k3t2mipiraw_YUV_Reprocess \
    libCamera_s5kgw1ofilmmipiraw_Face_Capture \
    libCamera_s5kgw1ofilmmipiraw_Face_Capture_64 \
    libCamera_s5kgw1ofilmmipiraw_Face_Preview \
    libCamera_s5kgw1ofilmmipiraw_Flash_Capture \
    libCamera_s5kgw1ofilmmipiraw_Flash_Preview_PF \
    libCamera_s5kgw1ofilmmipiraw_HDR_Scene_Capture \
    libCamera_s5kgw1ofilmmipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_s5kgw1ofilmmipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_s5kgw1ofilmmipiraw_MFSR_Scene_Capture \
    libCamera_s5kgw1ofilmmipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_s5kgw1ofilmmipiraw_MFSR_Scene_Capture_Zoom2 \
    libCamera_s5kgw1ofilmmipiraw_QQ_Capture \
    libCamera_s5kgw1ofilmmipiraw_QQ_Capture_ChatMode \
    libCamera_s5kgw1ofilmmipiraw_Reserved \
    libCamera_s5kgw1ofilmmipiraw_Scene_Capture \
    libCamera_s5kgw1ofilmmipiraw_Scene_Capture_64 \
    libCamera_s5kgw1ofilmmipiraw_Scene_Preview \
    libCamera_s5kgw1ofilmmipiraw_Scene_Preview_Zoom1 \
    libCamera_s5kgw1ofilmmipiraw_Scene_Preview_Zoom2 \
    libCamera_s5kgw1ofilmmipiraw_SuperNS_Face_Preview \
    libCamera_s5kgw1ofilmmipiraw_SuperNS_Scene_Capture \
    libCamera_s5kgw1ofilmmipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_s5kgw1ofilmmipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_s5kgw1ofilmmipiraw_SuperNS_Scene_Preview \
    libCamera_s5kgw1ofilmmipiraw_Torch_Capture \
    libCamera_s5kgw1ofilmmipiraw_Video \
    libCamera_s5kgw1ofilmmipiraw_Video_1080P_60fps \
    libCamera_s5kgw1ofilmmipiraw_Video_1080P_EIS \
    libCamera_s5kgw1ofilmmipiraw_Video_480P \
    libCamera_s5kgw1ofilmmipiraw_Video_4K \
    libCamera_s5kgw1ofilmmipiraw_Video_4K_Zoom1 \
    libCamera_s5kgw1ofilmmipiraw_Video_4K_Zoom2 \
    libCamera_s5kgw1ofilmmipiraw_Video_720P \
    libCamera_s5kgw1ofilmmipiraw_Video_720P_1080P_120fps \
    libCamera_s5kgw1ofilmmipiraw_Video_720P_240fps \
    libCamera_s5kgw1ofilmmipiraw_Video_720P_EIS \
    libCamera_s5kgw1ofilmmipiraw_Video_EIS_Default \
    libCamera_s5kgw1ofilmmipiraw_Video_Zoom1 \
    libCamera_s5kgw1ofilmmipiraw_Video_Zoom2 \
    libCamera_s5kgw1ofilmmipiraw_portrait_capture_full \
    libCamera_s5kgw1ofilmmipiraw_portrait_preview_full \
    libCamera_s5kgw1sunnymipiraw_Face_Capture \
    libCamera_s5kgw1sunnymipiraw_Face_Capture_64 \
    libCamera_s5kgw1sunnymipiraw_Face_Preview \
    libCamera_s5kgw1sunnymipiraw_Flash_Capture \
    libCamera_s5kgw1sunnymipiraw_Flash_Preview_PF \
    libCamera_s5kgw1sunnymipiraw_HDR_Scene_Capture \
    libCamera_s5kgw1sunnymipiraw_HDR_Scene_Capture_Zoom1 \
    libCamera_s5kgw1sunnymipiraw_HDR_Scene_Capture_Zoom2 \
    libCamera_s5kgw1sunnymipiraw_MFSR_Scene_Capture \
    libCamera_s5kgw1sunnymipiraw_MFSR_Scene_Capture_Zoom1 \
    libCamera_s5kgw1sunnymipiraw_MFSR_Scene_Capture_Zoom2 \
    libCamera_s5kgw1sunnymipiraw_QQ_Capture \
    libCamera_s5kgw1sunnymipiraw_QQ_Capture_ChatMode \
    libCamera_s5kgw1sunnymipiraw_Reserved \
    libCamera_s5kgw1sunnymipiraw_Scene_Capture \
    libCamera_s5kgw1sunnymipiraw_Scene_Capture_64 \
    libCamera_s5kgw1sunnymipiraw_Scene_Capture_HWNR \
    libCamera_s5kgw1sunnymipiraw_Scene_Preview \
    libCamera_s5kgw1sunnymipiraw_Scene_Preview_Zoom1 \
    libCamera_s5kgw1sunnymipiraw_Scene_Preview_Zoom2 \
    libCamera_s5kgw1sunnymipiraw_SuperNS_Face_Preview \
    libCamera_s5kgw1sunnymipiraw_SuperNS_Scene_Capture \
    libCamera_s5kgw1sunnymipiraw_SuperNS_Scene_Capture_Zoom1 \
    libCamera_s5kgw1sunnymipiraw_SuperNS_Scene_Capture_Zoom2 \
    libCamera_s5kgw1sunnymipiraw_SuperNS_Scene_Preview \
    libCamera_s5kgw1sunnymipiraw_Torch_Capture \
    libCamera_s5kgw1sunnymipiraw_Video \
    libCamera_s5kgw1sunnymipiraw_Video_1080P_60fps \
    libCamera_s5kgw1sunnymipiraw_Video_1080P_EIS \
    libCamera_s5kgw1sunnymipiraw_Video_480P \
    libCamera_s5kgw1sunnymipiraw_Video_4K \
    libCamera_s5kgw1sunnymipiraw_Video_4K_Zoom1 \
    libCamera_s5kgw1sunnymipiraw_Video_4K_Zoom2 \
    libCamera_s5kgw1sunnymipiraw_Video_720P \
    libCamera_s5kgw1sunnymipiraw_Video_720P_1080P_120fps \
    libCamera_s5kgw1sunnymipiraw_Video_720P_240fps \
    libCamera_s5kgw1sunnymipiraw_Video_720P_EIS \
    libCamera_s5kgw1sunnymipiraw_Video_EIS_Default \
    libCamera_s5kgw1sunnymipiraw_Video_Zoom1 \
    libCamera_s5kgw1sunnymipiraw_Video_Zoom2 \
    libCamera_s5kgw1sunnymipiraw_portrait_capture_full \
    libCamera_s5kgw1sunnymipiraw_portrait_preview_full \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libVDSuperPhotoAPI \
    libabfadp \
    libalCFR \
    libalLDC \
    libalRnBRT_GL_GBWRAPPER \
    libalhLDC \
    libapu-apuwareutils.mtk \
    libapu-apuwarexrp.mtk \
    libapu-frontend \
    libapu-platform \
    libapusys \
    libarcsoft_beautyshot \
    libarcsoft_dualcam_refocus \
    libarcsoft_high_dynamic_range \
    libarcsoft_low_light_hdr \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_preview_deflicker \
    libarmnn-vendor \
    libarmnn_ndk.mtk \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbluetooth_relayer \
    libbluetoothem_mtk \
    libbt-vendor \
    libc++_shared \
    libcam.ArcCamEngine \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3 \
    libcam.halisp \
    libcam.halsensor \
    libcam.iopipe \
    libcam.lcs \
    libcam.pdtblgen \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam3a_imem \
    libcamalgo.3dnr \
    libcamalgo.asd \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.flicker \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.ispfeature \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.n3d \
    libcamalgo.utility \
    libcamalgo.vpunr \
    libcamalgo.vsf \
    libcamalgo.warp \
    libcamdrv_imem \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera_scene \
    libcameracustom.eis \
    libcameracustom \
    libchromanr \
    libcmdl \
    libcmdl_ndk.mtk \
    libdip_drv \
    libdip_imem \
    libdip_postproc \
    libdlbdsservice \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libforkexecwrap \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libifcutils_mtk \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    libimgsensorca \
    libksensor \
    liblpcnr \
    libmfllcore \
    libmialgo_sd \
    libmialgoengine \
    libmibokeh_mt6785 \
    libmpbase \
    libmtk-ril \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_3rdparty.vidhance \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3 \
    libmtkcam_device3_app \
    libmtkcam_dpe \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_feature \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_hbc \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_sysutils \
    libmtkcam_tsf \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkconfig \
    libmtkconfigutils \
    libmtkrilutils \
    libmtktinyxml \
    libmtkutils \
    libneuroeara \
    libneuron_adapter \
    libneuron_platform \
    libneuron_runtime \
    libneuropilot_hal_utils \
    libneuropilot_jni_R \
    libnir_neon_driver_ndk.mtk \
    libratconfig \
    librilfusion \
    libsensor_custom \
    libstereoinfoaccessor_vsdof \
    libvia-ril \
    libvidhance \
    libwifi-hal-mtk \
    ov02a10af_mipi_raw_IdxMgr \
    ov02a10af_mipi_raw_tuning \
    ov02a10alpha_mipi_raw_IdxMgr \
    ov02a10alpha_mipi_raw_tuning \
    ov02a10beta_mipi_raw_IdxMgr \
    ov02a10beta_mipi_raw_tuning \
    ov8856ofilm_mipi_raw_IdxMgr \
    ov8856ofilm_mipi_raw_tuning \
    ov8856sunny_mipi_raw_IdxMgr \
    ov8856sunny_mipi_raw_tuning \
    s5k3t1ofilm_mipi_raw_IdxMgr \
    s5k3t1ofilm_mipi_raw_tuning \
    s5k3t1sunny_mipi_raw_IdxMgr \
    s5k3t1sunny_mipi_raw_tuning \
    s5k3t2_mipi_raw_IdxMgr \
    s5k3t2_mipi_raw_tuning \
    s5kgw1ofilm_mipi_raw_IdxMgr \
    s5kgw1ofilm_mipi_raw_tuning \
    s5kgw1sunny_mipi_raw_IdxMgr \
    s5kgw1sunny_mipi_raw_tuning \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.mediatek.hardware.apuware.utils@1.0 \
    vendor.mediatek.hardware.apuware.xrp@1.0 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.engineermode@1.0 \
    vendor.mediatek.hardware.engineermode@1.1 \
    vendor.mediatek.hardware.engineermode@1.2 \
    vendor.mediatek.hardware.engineermode@1.3 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.microtrust.hardware.soter@1.0 \
    wechat.beanpod \
    vendor.mediatek.hardware.videotelephony@1.0 \
    EngineerMode \
    ImsService \
    SoterService \
    mediatek-common \
    mediatek-framework \
    mediatek-ims-base \
    mediatek-ims-common \
    mediatek-ims-extension-plugin \
    mediatek-ims-legacy \
    mediatek-telecom-common \
    mediatek-telephony-base \
    mediatek-telephony-common \
    android.hardware.biometrics.fingerprint@2.1-service.xml \
    android.hardware.gpu@1.0-service.xml \
    android.hardware.neuralnetworks@1.3-service-mtk-dsp-gpu.xml \
    fp_manifest.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    manifest_vendor.dolby.hardware.dms.xml \
    vtservice \
    batteryd \
    bp_kmsetkey_ca \
    ccci_fsd \
    ccci_mdinit \
    ccci_rpcd \
    em_hidl \
    epdg_wod \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gnss@2.1-service-mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.0-service.beanpod \
    android.hardware.neuralnetworks@1.3-service-mtk-neuron \
    android.hardware.sensors@1.0-service-mediatek \
    android.hardware.thermal@2.0-service.mtk \
    android.hardware.usb@1.1-service-mediatek \
    camerahalserver \
    mfp-daemon \
    mtkfusionrild \
    vendor.dolby.hardware.dms@2.0-service \
    vendor.mediatek.hardware.dfps@1.0-service \
    vendor.mediatek.hardware.gpu@1.0-service \
    vendor.mediatek.hardware.mms@1.5-service \
    vendor.mediatek.hardware.mtkcodecservice@1.1-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.microtrust.hardware.soter@1.0-service \
    vtservice_hidl \
    lib3a.ccu.ddr \
    lib3a.ccu.dm \
    lib3a.ccu.pm \
    libccu_gc2375af_mipi_raw.ddr \
    libccu_gc2375alpha_mipi_raw.ddr \
    libccu_gc2375beta_mipi_raw.ddr \
    libccu_gc5035_mipi_raw.ddr \
    libccu_ov02a10af_mipi_raw.ddr \
    libccu_ov02a10alpha_mipi_raw.ddr \
    libccu_ov02a10beta_mipi_raw.ddr \
    libccu_ov8856ofilm_mipi_raw.ddr \
    libccu_ov8856sunny_mipi_raw.ddr \
    libccu_s5k3t1ofilm_mipi_raw.ddr \
    libccu_s5k3t1sunny_mipi_raw.ddr \
    libccu_s5k3t2_mipi_raw.ddr \
    libccu_s5kgw1ofilm_mipi_raw.ddr \
    libccu_s5kgw1sunny_mipi_raw.ddr \
    mi_thermald \
    mnld \
    mtk_agpsd \
    muxreport \
    netdagent \
    nvram_daemon \
    rttv \
    starter \
    stroke \
    teei_daemon \
    thermal \
    thermal_manager \
    thermalloadalgod \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_stack \
    volte_ua \
    vpud \
    wfca \
    wlan_assistant \
    wmt_launcher \
    wmt_loader \
    xcap

PRODUCT_PACKAGES += \
    vendor_lib_hw_vulkan_mt6785_so \
    vendor_lib64_hw_vulkan_mt6785_so
